In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

DF Hechos

In [17]:
#Cargamos DF Hechos
df_h = pd.read_csv('Datasets\homicidios.xlsx - HECHOS.csv')
df_h

<>:2: SyntaxWarning: invalid escape sequence '\h'
<>:2: SyntaxWarning: invalid escape sequence '\h'
C:\Users\Admin\AppData\Local\Temp\ipykernel_1592\4184851358.py:2: SyntaxWarning: invalid escape sequence '\h'
  df_h = pd.read_csv('Datasets\homicidios.xlsx - HECHOS.csv')

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,1/1/2016,2016,1,1,4:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,1/2/2016,2016,1,2,1:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,1/3/2016,2016,1,3,7:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,1/10/2016,2016,1,10,0:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,MOTO,SD
4,2016-0005,1,1/21/2016,2016,1,21,5:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,12/13/2021,2021,12,13,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,...,NaN,MOM,RIESTRA AV. y MOM,7,Point (102728.60090138 98186.24929177),-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,12/20/2021,2021,12,20,1:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,NaN,LACARRA AV.,"DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.",9,Point (99624.29795829 97569.69801131),-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,12/30/2021,2021,12,30,0:43:00,0,AV. GAONA Y TERRADA,AVENIDA,...,NaN,TERRADA,GAONA AV. y TERRADA,11,Point (99116.45492358 101045.23284826),-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,12/15/2021,2021,12,15,10:30:00,10,AV. EVA PERON 4071,AVENIDA,...,4071.0,NaN,"PERON, EVA AV. 4071",9,Point (99324.54463985 97676.26932409),-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,11/18/2021,2021,11,18,6:10:00,6,PADRE CARLOS MUJICA 709,CALLE,...,709.0,NaN,PADRE CARLOS MUGICA 709,1,Point (107664.16647795 104708.63962087),-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

In [18]:
# Se rellenan los valores faltantes en la columna 'Dirección normalizada' con los valores de la columna 'LUGAR_DEL_HECHO' 
df_h['Dirección Normalizada'].fillna(df_h['LUGAR_DEL_HECHO'], inplace=True)

# Se chequea la cantidad de nulos en la columna 'Dirección Normalizada'
df_h['Dirección Normalizada'].isna().sum()

C:\Users\Admin\AppData\Local\Temp\ipykernel_1592\301299970.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_h['Dirección Normalizada'].fillna(df_h['LUGAR_DEL_HECHO'], inplace=True)

0

In [19]:
# Se eliminan las columnas
df_h = df_h.drop(['LUGAR_DEL_HECHO', 'Calle', 'Altura'], axis=1)
# Cambio el nombre de la columna 'Dirección Normalizada' a 'LUGAR DEL HECHO'
df_h = df_h.rename(columns={'Dirección Normalizada': 'Lugar del Hecho'})

# Se confirma 
df_h.columns

Index(['ID', 'N_VICTIMAS', 'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH',
       'TIPO_DE_CALLE', 'Cruce', 'Lugar del Hecho', 'COMUNA', 'XY (CABA)',
       'pos x', 'pos y', 'PARTICIPANTES', 'VICTIMA', 'ACUSADO'],
      dtype='object')

In [20]:
# Se reemplazan los valores NULOS por "No" y los NO NULOS por "Si" 
#Permite analizar mas facilmente si un siniestro fue en un cruce o no
df_h['Cruce'] = np.where(df_h['Cruce'].notnull(), 'SI', 'NO')

# Se revisa la columna
df_h[['Cruce', 'Lugar del Hecho']]

    Cruce                                    Lugar del Hecho
0      SI  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...
1      SI               PAZ, GRAL. AV. y DE LOS CORRALES AV.
2      NO                                ENTRE RIOS AV. 2034
3      SI          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.
4      SI            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.
..    ...                                                ...
691    SI                                  RIESTRA AV. y MOM
692    SI         DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.
693    SI                                GAONA AV. y TERRADA
694    NO                                PERON, EVA AV. 4071
695    NO                            PADRE CARLOS MUGICA 709

[696 rows x 2 columns]

In [22]:
#Renombrar columnas
# Se coloca la primera en mayúscula
df_h.columns = [x.capitalize() for x in df_h.columns]

# Se reemplazan los guiones por espacios
df_h.columns = df_h.columns.str.replace('_', ' ')

# Se renombran algunas columnas
df_h = df_h.rename(columns={'N victimas': 'Nro Víctimas',
                            'Aaaa':'Año',
                            'Mm':'Mes',
                            'Dd':'Día',
                            'Hh':'Hora Estandar',
                            'Xy (caba)':'XY (CABA)',
                            'Victima':'Víctima'})
df_h.columns

Index(['Id', 'Nro víctimas', 'Fecha', 'Año', 'Mes', 'Día', 'Hora',
       'Hora estandar', 'Tipo de calle', 'Cruce', 'Lugar del hecho', 'Comuna',
       'XY (CABA)', 'Pos x', 'Pos y', 'Participantes', 'Víctima', 'Acusado'],
      dtype='object')

In [23]:
# Utilización de regex para corregir los valores
df_h.replace(to_replace=['Ã‘', r'\?'], value=['Ñ', 'Ñ'], regex=True, inplace=True)

In [24]:
#Mostrar filas duplicadas
duplicadas = df_h[df_h.duplicated(subset='Id', keep=False)]
duplicadas

Empty DataFrame
Columns: [Id, Nro víctimas, Fecha, Año, Mes, Día, Hora, Hora estandar, Tipo de calle, Cruce, Lugar del hecho, Comuna, XY (CABA), Pos x, Pos y, Participantes, Víctima, Acusado]
Index: []

In [25]:
# Función que convierte un valor a un objeto de tiempo (time) de Python, si es posible
def convertir_a_hora(x):
    if isinstance(x, str):
        try:
            return datetime.strptime(x, "%H:%M:%S").time()
        except ValueError:
            return None
    elif isinstance(x, datetime):
        return x.time()
    return x

# Se cambia el tipo de dato en la columna 'Hora'
df_h['Hora'] = df_h['Hora'].apply(lambda x: convertir_a_hora(x))

df_h[df_h['Hora'].isna()]

,Id,Nro víctimas,Fecha,Año,Mes,Día,Hora,Hora estandar,Tipo de calle,Cruce,Lugar del hecho,Comuna,XY (CABA),Pos x,Pos y,Participantes,Víctima,Acusado
518,2019-0103,1,12/18/2019,2019,12,18,None,SD,GRAL PAZ,SI,"PAZ, GRAL. AV. y GRIVEO",11,Point (94643.11254058 103831.57115061),-58.52169422,-34.59471640,MOTO-MOTO,MOTO,MOTO

In [26]:
# Se calcula la hora mas común
hora_mas = df_h['Hora'].mode().iloc[0]

# Se reemplaza el valor None por la hora más común
df_h['Hora'].fillna(hora_mas, inplace=True)

# Se verifica el tipo de dato para la columna
df_h['Hora'].apply(type).value_counts()

C:\Users\Admin\AppData\Local\Temp\ipykernel_1592\995316040.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_h['Hora'].fillna(hora_mas, inplace=True)

Hora
<class 'datetime.time'>    696
Name: count, dtype: int64

In [29]:
# Se imputa la hora moda al dato faltante
df_h['Hora Estandar'] = df_h['Hora estandar'].apply(lambda x: int(hora_mas.hour) if x == "SD" else x)

# Se verifica el tipo de dato
#df_h['Hora Estandar'].apply(type).value_counts()

Hora Estandar
<class 'str'>    695
<class 'int'>      1
Name: count, dtype: int64

In [30]:
#Valores unicos de la col Victima
df_h['Víctima'].unique()

array(['MOTO', 'AUTO', 'PEATON', 'SD', 'CARGAS', 'BICICLETA', 'PASAJEROS',
       'MOVIL', 'OBJETO FIJO', 'PEATON_MOTO'], dtype=object)

In [31]:
# Se modifican los valores fuera del diccionario de datos, segun el dataset original
df_h['Víctima'] = df_h['Víctima'].replace({'OBJETO FIJO':'AUTO', 'PEATON_MOTO':'PEATON'})

In [32]:
# Aplico una función lambda para reemplazar 'OBJETO FIJO' con el valor de 'Víctima'
df_h['Acusado'] = df_h.apply(
    lambda fila: fila['Víctima'] if fila['Acusado'] == 'OBJETO FIJO' else fila['Acusado'],
    axis=1
)

In [33]:
# Se analizan los registro vacíos en 'XY (CABA)'
df_h[df_h['XY (CABA)']=='Point (. .)']

,Id,Nro víctimas,Fecha,Año,Mes,Día,Hora,Hora estandar,Tipo de calle,Cruce,Lugar del hecho,Comuna,XY (CABA),Pos x,Pos y,Participantes,Víctima,Acusado,Hora Estandar
35,2016-0049,1,4/17/2016,2016,4,17,00:00:00,0,AUTOPISTA,NO,AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI,4,Point (. .),-58.37714647568196,-34.63657525428238,SD-SD,SD,SD,0
38,2016-0052,1,4/20/2016,2016,4,20,20:00:00,20,AUTOPISTA,NO,AUTOPISTA LUGONES PK 10000,13,Point (. .),.,.,MOTO-SD,MOTO,SD,20
71,2016-0096,1,7/25/2016,2016,7,25,07:00:00,7,AUTOPISTA,NO,AUTOPISTA DELLEPIANE LUIS TTE. GRAL.,8,Point (. .),-58.47433193007387,-34.66684950051973,MOTO-CARGAS,MOTO,CARGAS,7
106,2016-0136,1,10/25/2016,2016,10,25,00:00:00,0,AUTOPISTA,NO,AU BUENOS AIRES - LA PLATA KM. 4,4,Point (. .),.,.,MOTO-CARGAS,MOTO,CARGAS,0
119,2016-0151,1,11/18/2016,2016,11,18,20:35:00,20,CALLE,NO,SD,0,Point (. .),.,.,PEATON-SD,PEATON,SD,20
139,2016-0174,1,12/27/2016,2016,12,27,00:00:00,0,AUTOPISTA,NO,AUTOPISTA 25 DE MAYO,0,Point (. .),.,.,SD-SD,SD,SD,0
176,2017-0042,1,4/10/2017,2017,4,10,09:00:00,9,GRAL PAZ,NO,"LUGONES, LEOPOLDO AV.",14,Point (. .),.,.,MOTO-CARGAS,MOTO,CARGAS,9
180,2017-0050,2,4/28/2017,2017,4,28,11:08:08,11,AUTOPISTA,NO,AU PERITO MORENO Y RAMAL ENLACE AU1/AU6,9,Point (. .),.,.,MOTO-CARGAS,MOTO,CARGAS,11
181,2017-0051,1,5/1/2017,2017,5,1,03:47:47,3,AUTOPISTA,NO,AU DELLEPIANE 2400,7,Point (. .),.,.,AUTO-AUTO,AUTO,AUTO,3
256,2017-0140,1,11/19/2017,2017,11,19,23:22:17,23,AUTOPISTA,NO,AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI,4,Point (. .),.,.,MOTO-PASAJEROS,MOTO,PASAJEROS,23
313,2018-0039,1,4/21/2018,2018,4,21,22:15:00,22,AUTOPISTA,NO,AUTOPISTA LUGONES KM 4.7,14,Point (. .),.,.,PEATON-AUTO,PEATON,AUTO,22
546,2020-0026,1,5/17/2020,2020,5,17,06:40:00,6,AUTOPISTA,NO,"LUGONES, LEOPOLDO AV. KM 6,1",14,Point (. .),.,.,MOTO-OBJETO FIJO,MOTO,MOTO,6
559,2020-0039,1,9/1/2020,2020,9,1,19:17:42,19,CALLE,NO,MURGUIONDO,9,Point (. .),.,.,PEATON-CARGAS,PEATON,CARGAS,19
621,2021-0023,1,3/1/2021,2021,3,1,09:20:00,9,AUTOPISTA,NO,"AU BUENOS AIRES LA PLATA KM 4,5",4,Point (. .),.,.,MOTO-CARGAS,MOTO,CARGAS,9

In [34]:
# Se elimina la columna 'XY (CABA)'
df_h = df_h.drop(['XY (CABA)'], axis=1)

# Se reemplazan los valores faltantes por 0 en las columnas X e Y
df_h['Pos x'] = df_h['Pos x'].replace('.', 0)
df_h['Pos y'] = df_h['Pos y'].replace('.', 0)

In [36]:
#Se deja el Dataframe listo para merge con el Dataframe Víctimas, copiando las filas que tienen valor mayor a 1 en el número de víctimas
#ya que el dataset 'víctimas' contiene una fila por cada víctima, en siniestros con multiples víctimas
# Se crea un nuevo Dataframe que contiene filas adicionales en caso de que haya mas de 1 víctima
filas_expandidas = []

for index, row in df_h.iterrows():
    n_victimas = row['Nro víctimas']
    
    if n_victimas > 1:
        filas_adicionales = pd.DataFrame([row] * (n_victimas - 1))
        
        # Se agregan las filas adicionales 
        filas_expandidas.append(filas_adicionales)

# Se concatena el Dataframe original con el que tiene las filas adicionales
df_h = pd.concat([df_h] + filas_expandidas, ignore_index=True)

In [38]:
df_h.head()

,Id,Nro víctimas,Fecha,Año,Mes,Día,Hora,Hora estandar,Tipo de calle,Cruce,Lugar del hecho,Comuna,Pos x,Pos y,Participantes,Víctima,Acusado,Hora Estandar
0,2016-0001,1,1/1/2016,2016,1,1,04:00:00,4,AVENIDA,SI,"PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,4
1,2016-0002,1,1/2/2016,2016,1,2,01:15:00,1,GRAL PAZ,SI,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,1
2,2016-0003,1,1/3/2016,2016,1,3,07:00:00,7,AVENIDA,NO,ENTRE RIOS AV. 2034,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,7
3,2016-0004,1,1/10/2016,2016,1,10,00:00:00,0,AVENIDA,SI,"LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,0
4,2016-0005,1,1/21/2016,2016,1,21,05:20:00,5,AVENIDA,SI,"SAN JUAN AV. y SAENZ PEÑA, LUIS, PRES.",1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,5

DF Victimas - ETL

In [3]:
#Cargamos DF Victimas
df_v = pd.read_csv('Datasets\homicidios.xlsx - VICTIMAS.csv')
df_v

<>:1: SyntaxWarning: invalid escape sequence '\h'
<>:1: SyntaxWarning: invalid escape sequence '\h'
C:\Users\Admin\AppData\Local\Temp\ipykernel_1592\2227317529.py:1: SyntaxWarning: invalid escape sequence '\h'
  df_v = pd.read_csv('Datasets\homicidios.xlsx - VICTIMAS.csv')

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1/1/2016,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,1/1/2016
1,2016-0002,1/2/2016,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70,1/2/2016
2,2016-0003,1/3/2016,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30,1/3/2016
3,2016-0004,1/10/2016,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,1/21/2016,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29,2/1/2016
...,...,...,...,...,...,...,...,...,...,...
712,2021-0092,12/12/2021,2021,12,12,PEATON,PEATON,FEMENINO,50,12/12/2021
713,2021-0093,12/13/2021,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18,12/18/2021
714,2021-0094,12/20/2021,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43,12/20/2021
715,2021-0095,12/30/2021,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27,1/2/2022
716,2021-0096,12/15/2021,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60,12/20/2021

In [39]:
# Se realiza un merge para combinar al dataframe homicidios solo las columnas nuevas del dataset de la pestaña víctimas
df_homicidios = df_h.merge(
    df_v[['ID_hecho', 'ROL', 'SEXO', 'EDAD', 'FECHA_FALLECIMIENTO']],
    left_on='Id', right_on='ID_hecho', how='left')

# Se elimina la columna duplicada 'ID_hecho' a partir de la cual se realizó el merge con 'Id'
df_homicidios.drop(columns='ID_hecho', inplace=True)
df_homicidios.head()

,Id,Nro víctimas,Fecha,Año,Mes,Día,Hora,Hora estandar,Tipo de calle,Cruce,...,Pos x,Pos y,Participantes,Víctima,Acusado,Hora Estandar,ROL,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,1/1/2016,2016,1,1,04:00:00,4,AVENIDA,SI,...,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,4,CONDUCTOR,MASCULINO,19,1/1/2016
1,2016-0002,1,1/2/2016,2016,1,2,01:15:00,1,GRAL PAZ,SI,...,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,1,CONDUCTOR,MASCULINO,70,1/2/2016
2,2016-0003,1,1/3/2016,2016,1,3,07:00:00,7,AVENIDA,NO,...,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,7,CONDUCTOR,MASCULINO,30,1/3/2016
3,2016-0004,1,1/10/2016,2016,1,10,00:00:00,0,AVENIDA,SI,...,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,0,CONDUCTOR,MASCULINO,18,SD
4,2016-0005,1,1/21/2016,2016,1,21,05:20:00,5,AVENIDA,SI,...,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,5,CONDUCTOR,MASCULINO,29,2/1/2016

In [43]:
# Se chequean las filas duplicadas, cuando coinciden 'Id', 'Nro Víctimas' y 'ROL' 
filas_duplicadas = df_homicidios[df_homicidios.duplicated(subset=["Id", "Nro víctimas", "ROL"], keep=False)]
filas_duplicadas

,Id,Nro víctimas,Fecha,Año,Mes,Día,Hora,Hora estandar,Tipo de calle,Cruce,...,Pos x,Pos y,Participantes,Víctima,Acusado,Hora Estandar,ROL,SEXO,EDAD,FECHA_FALLECIMIENTO
29,2016-0041,2,3/29/2016,2016,3,29,11:00:00,11,AVENIDA,SI,...,-58.46076550,-34.63350444,MOTO-CARGAS,MOTO,CARGAS,11,CONDUCTOR,MASCULINO,54,3/29/2016
30,2016-0041,2,3/29/2016,2016,3,29,11:00:00,11,AVENIDA,SI,...,-58.46076550,-34.63350444,MOTO-CARGAS,MOTO,CARGAS,11,PASAJERO_ACOMPAÑANTE,MASCULINO,SD,3/30/2016
98,2016-0126,2,9/18/2016,2016,9,18,22:45:00,22,CALLE,SI,...,-58.52572109,-34.62125906,AUTO-CARGAS,AUTO,CARGAS,22,CONDUCTOR,MASCULINO,37,SD
99,2016-0126,2,9/18/2016,2016,9,18,22:45:00,22,CALLE,SI,...,-58.52572109,-34.62125906,AUTO-CARGAS,AUTO,CARGAS,22,PASAJERO_ACOMPAÑANTE,MASCULINO,60,SD
163,2017-0026,2,2/26/2017,2017,2,26,05:15:00,5,AVENIDA,SI,...,-58.41842777,-34.64979057,AUTO-OBJETO FIJO,AUTO,AUTO,5,PASAJERO_ACOMPAÑANTE,FEMENINO,23,2/26/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,2020-0038,2,8/30/2020,2020,8,30,04:00:00,4,AVENIDA,SI,...,-58.40617526,-34.58345898,AUTO-AUTO,AUTO,AUTO,4,CONDUCTOR,MASCULINO,64,8/30/2020
757,2020-0063,2,12/5/2020,2020,12,5,07:10:00,7,CALLE,SI,...,-58.52783814,-34.61047001,PEATON_MOTO-MOTO,PEATON,MOTO,7,PEATON,MASCULINO,38,12/5/2020
758,2020-0063,2,12/5/2020,2020,12,5,07:10:00,7,CALLE,SI,...,-58.52783814,-34.61047001,PEATON_MOTO-MOTO,PEATON,MOTO,7,PASAJERO_ACOMPAÑANTE,MASCULINO,21,12/5/2020
759,2020-0077,2,12/25/2020,2020,12,25,06:40:00,6,AVENIDA,SI,...,-58.47220945,-34.60111373,MOTO-AUTO,MOTO,AUTO,6,CONDUCTOR,FEMENINO,30,12/25/2020
760,2020-0077,2,12/25/2020,2020,12,25,06:40:00,6,AVENIDA,SI,...,-58.47220945,-34.60111373,MOTO-AUTO,MOTO,AUTO,6,PASAJERO_ACOMPAÑANTE,FEMENINO,24,12/25/2020

In [47]:
# Se eliminan las columnas duplicadas, que coincidan con el criterio aplicado para buscar duplicados
df_homicidios = df_homicidios.drop_duplicates(subset=["Id", "Nro víctimas", "ROL"], keep=False)

In [53]:
#Completar valores NaN con 0 
df_homicidios['EDAD'].fillna(0, inplace=True)
#Convertir tipo de dato a INT 
df_homicidios['EDAD'] = df_homicidios['EDAD'].astype(int)

In [54]:

# Calcular el promedio de la columna 'Edad' agrupada por 'Sexo' y convertirlo a parte entera
promedio_por_sexo = df_homicidios.groupby('SEXO')['EDAD'].mean().apply(lambda x: int(x) if not pd.isna(x) else pd.NA).to_dict()

# Imputar los valores NaN en la columna 'Edad' con el promedio correspondiente al 'Sexo'
df_homicidios['EDAD'] = df_homicidios.apply(lambda row: promedio_por_sexo[row['SEXO']] if pd.isna(row['EDAD']) and row['SEXO'] != 'SD' else 30 if pd.isna(row['EDAD']) and row['SEXO'] == 'SD' else row['EDAD'], axis=1)

In [56]:
# Calcular la moda de la columna "Comuna" para reemplazarlo
moda_comuna = df_homicidios['Comuna'].mode()[0]

# Reemplazar los valores 0 por la moda de la columna "Comuna" (la comuna 0 no existe)
df_homicidios['Comuna'] = df_homicidios['Comuna'].replace(0, moda_comuna)

In [57]:
def moda_faltante(df, columna):
    # Se reemplaza "SD" con NaN en la columna
    df[columna] = df[columna].replace('SD', pd.NA)

    # Se calcula el valor más frecuente en la columna
    valor_mas_frecuente = df[columna].mode().iloc[0]

    # Se imputan los valores NaN con el valor más frecuente
    df[columna].fillna(valor_mas_frecuente, inplace=True)


# Imputa valor mas frecuente en la columna rol
moda_faltante(df_homicidios, 'ROL')

# Imputa valor mas frecuente en la columna víctima
moda_faltante(df_homicidios, 'Víctima')

C:\Users\Admin\AppData\Local\Temp\ipykernel_1592\4067127413.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[columna].fillna(valor_mas_frecuente, inplace=True)

In [59]:
# Convierte la columna fecha a datetime, extrae el día de la semana y el mes y crea nuevas columnas "DIA" y "MES"
dias_español = {
    'Monday': 'Lunes',
    'Tuesday': 'Martes',
    'Wednesday': 'Miércoles',
    'Thursday': 'Jueves',
    'Friday': 'Viernes',
    'Saturday': 'Sábado',
    'Sunday': 'Domingo',
}

meses_español = {
    'January': 'Enero',
    'February': 'Febrero',
    'March': 'Marzo',
    'April': 'Abril',
    'May': 'Mayo',
    'June': 'Junio',
    'July': 'Julio',
    'August': 'Agosto',
    'September': 'Septiembre',
    'October': 'Octubre',
    'November': 'Noviembre',
    'December': 'Diciembre',
}

df_homicidios['Fecha'] = pd.to_datetime(df_homicidios['Fecha'])
df_homicidios['Día'] = df_homicidios['Fecha'].dt.day_name().map(dias_español)
df_homicidios['Mes'] = df_homicidios['Fecha'].dt.month_name().map(meses_español)
df_homicidios['Fecha'] = df_homicidios['Fecha'].dt.date

In [60]:
# Se eliminan las columnas
df_homicidios = df_homicidios.drop(['Fecha', 'Hora'], axis=1)
df_homicidios.head()

,Id,Nro víctimas,Año,Mes,Día,Hora estandar,Tipo de calle,Cruce,Lugar del hecho,Comuna,Pos x,Pos y,Participantes,Víctima,Acusado,Hora Estandar,ROL,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,1,2016,Enero,Viernes,4,AVENIDA,SI,"PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO,4,CONDUCTOR,MASCULINO,19,1/1/2016
1,2016-0002,1,2016,Enero,Sábado,1,GRAL PAZ,SI,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS,1,CONDUCTOR,MASCULINO,70,1/2/2016
2,2016-0003,1,2016,Enero,Domingo,7,AVENIDA,NO,ENTRE RIOS AV. 2034,1,-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO,7,CONDUCTOR,MASCULINO,30,1/3/2016
3,2016-0004,1,2016,Enero,Domingo,0,AVENIDA,SI,"LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,-58.46503904,-34.68092974,MOTO-SD,MOTO,SD,0,CONDUCTOR,MASCULINO,18,SD
4,2016-0005,1,2016,Enero,Jueves,5,AVENIDA,SI,"SAN JUAN AV. y SAENZ PEÑA, LUIS, PRES.",1,-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS,5,CONDUCTOR,MASCULINO,29,2/1/2016

In [61]:
# Se renombran algunas columnas
df_homicidios = df_homicidios.rename(columns={'ROL': 'Rol',
                                            'SEXO':'Sexo',
                                            'Hora Estandar':'Hora',
                                            'EDAD':'Edad'})
df_homicidios.columns

Index(['Id', 'Nro víctimas', 'Año', 'Mes', 'Día', 'Hora estandar',
       'Tipo de calle', 'Cruce', 'Lugar del hecho', 'Comuna', 'Pos x', 'Pos y',
       'Participantes', 'Víctima', 'Acusado', 'Hora', 'Rol', 'Sexo', 'Edad',
       'FECHA_FALLECIMIENTO'],
      dtype='object')

In [63]:
df_homicidios.to_csv(r"C:\Users\Admin\Downloads\Segundo Proyecto\Datasets\homicidios_clean.csv", index=False, encoding='utf-8')